app/urls.py
from django.urls import path
from . import views

app_name = 'app' 
urlpatterns=[
    path('index/', views.index, name='index'), 
    path('index/profesor/', views.profesor, name='profesor'), 
    path('index/admin/', views.admin, name='admin'), 
    path('index/estudiante/', views.estudiante, name='estudiante'), 



]

pagina_login/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    # return HttpResponse("Hola, mundo")
    return render(request, 'app/index.html')


def profesor(request):
    return render(request,'app/profesor.html')
    
def admin(request):
    return render(request,'app/admin.html')

def estudiante(request):
    return render(request,'app/estudiante.html')

app/templates/app/admin.html
{% load static %}
<html>
    <html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Admin</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
</head>

<body>
    <h1>Bienvenido Administrador</h1>

    <p class="InformacionUsuario">
        Andres Felipe Melo Suarez
        <br> id:100
        <br> Administrador@gmail.com
    </p>
    <a href="{% url 'app:index' %}">
        <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
    </a>
    <img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
    
    
    <br>
    <br>
    <a href="verListaEstudiantes.html" target="_blank">
        <input class="Boton" type="submit" value="Ver estudiantes">
    </a>
    <br>
    <br>
    <a href="verGruposComoAdmin.html" target="_blank">
        <input class="Boton" type="submit" value="Ver grupos">
    </a>
    <br>
    <br>
    <a href="verProfesores.html" target="_blank">
        <input class="Boton" type="submit" value="Ver profesores">
    </a>
    <br>
    <br>
    <a href="crearGrupoAdmin.html" target="_blank">
        <input class="Boton" type="submit" value="Crear grupo">
    </a>
    <br>
    <br>
    <a href="crearProfesor.html" target="_blank">
        <input class="Boton" type="submit" value="Crear profesor">
    </a>
    <br>
    <br>
    <a href="crearEstudiante.html" target="_blank">
        <input class="Boton" type="submit" value="Crear alumno">
    </a>
    <div class="logoxd">
        <img src="{% static 'app/img/logo-social.png' %}" alt="logo-social"></div>

   
</body>

</html>

app/templates/app/autenticacion.html
<html>
    <html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Proyecto Cloud</title>
    <link rel="stylesheet" href="css/estilo.css">
</head>

<body>
    <h1>BIENVENIDO A GRADER</h1>
    <form>
        <div class="autenticacion">

            <h2>USUARIO:</h2>
            <input type="" id="USUARIO">
            <br>
            <h2>CLAVE:</h2>
            <input type="password" id="password">
            <br>
            <br>
        </div>
        <input class="Boton" type="submit" value="Enviar">
    </form>
    <br>
    <br>
    <br>
    <img src="img/AWS.jpg" alt="AWS" width="150">
    <img class="usta" src="img/LOGO_USTA_AZUL.png" alt="Logo usta">
    <br>
    <a href="profesor" target="_blank">Ver como profesor</a>
    <br>
    <a href="admin.html" target="_blank">Ver como admin</a>
    <br>
    <a href="estudiante.html" target="_blank">Ver como estudiante</a>
    <br>

</body>

</html>

app/templates/app/crearGrupoAdmin.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>Crear Gupo</title>
    <link rel="stylesheet" href="css/estilocrearestudiante.css">
</head>

<body>
    <h1> CREAR GRUPO</h1>
    <hr>
    <br>
    <img src="img/profilephoto.png" alt="profilephoto" width="180">
    <img src="img/LOGO_USTA_AZUL.png" alt="Logo" class="logoustagrupo" width="200">

    <div class="admincreargrupo">

        <a href="index.html">
            <input class="cerrargrupo" type="submit" value="Cerrar Sesión">
        </a>

        <form class="asignatura">
            <label for="asignaturain" id="lblasignatura">Codigo del grupo </label>
            <input type="text" id="asignaturain" placeholder="Ingrese codigo del grupo" class="inasignatura">
        </form>
        <br>
        <br>
        <form class="semestre">
            <label for="semestrein" id="lblsemestre">Asignatura </label>
            <input type="text" id="semestrein" placeholder="Ingrese la asignatura" class="insemestre">
        </form>
        <br>
        <br>
        <form class="profesorgrupo">
            <label for="profesorin" id="lblprofesor">Profesor </label>
            <input type="text" id="profesorin" placeholder="Ingrese Profesor asignado" class="inprofesor">
        </form>
        <br>
        <br>

        <form class="cantidad">
            <label for="cantidadin" id="lblcantidad">Semestre </label>
            <input type="text" id="cantidadin" placeholder="Ingrese semestre" class="incantidad">
        </form>

    </div>
    <br>
    <input class="enviarGrupo" type="submit" value="Enviar">


    </form>
</body>

</html>

app/templates/app/crearProfesor.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/estiloCrearProfesor.css">

    <title>Crear Profesor</title>
</head>

<body>
    <div class="contenedor">
        <div class="title">
            <h1>Crear Profesor</h1>
            <hr>
        </div>

        <div class="Datos">
            <div class="FotoPerfil">
                <img src="img/profilephoto.png" alt="profilephoto" width="180">
            </div>
            <div class="nombres">
                Acción de administrador
            </div>
            <div class="cerrarsesion1">
                <a href="index.html">
                    <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
                </a>
            </div>
        </div>
        <div class="creacion">
            <div class="datosDelProfe">
                <label for="apellidosProfe">Apellidos:</label>
                <input type="text" name="apellidosProfe">
                <label for="apellidosProfe"><abbr title="required" aria-label="required"></abbr>*</abbr></label>
                <br>
                <label for="nombresProfe">Nombres:</label>
                <input type="text" name="nombresProfe">
                <label for="nombresProfe"><abbr title="required" aria-label="required"></abbr>*</abbr></label>
                <br>
                <label for="emailProfe">e-mail:</label>
                <input type="text" name="emailProfe">
                <label for="emailProfe"><abbr title="required" aria-label="required"></abbr>*</abbr></label>
                <form>
                    <!-- <fieldset></fieldset> -->
                    <legend>Cátedra:</legend>
                    <p>
                        <input type="radio" name="size" id="size_1" value="si">
                        <label for="size_1">Si</label>
                    </p>
                    <p>
                        <input type="radio" name="size" id="size_2" value="No">
                        <label for="size_2">No</label>
                    </p>
                </form>
                <label for="contraProfe">Contraseña:</label>
                <input type="text" name="contraProfe">
                <label for="contraProfe"><abbr title="required" aria-label="required"></abbr>*</abbr></label>
            </div>
            <div class="crearProfe">
                <input class="Boton" type="submit" value="Crear Profesor">
            </div>
        </div>
    </div>

</body>


</html>

app/templates/app/editarEstudiante.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>Editar Estudiante como admin</title>
    <link rel="stylesheet" href="css/estilocrearestudiante.css">
</head>

<body>
    <h1> EDITAR ESTUDIANTE</h1>
    <hr>
    <br>
    <img src="img/profilephoto.png" alt="profilephoto" width="180">
    <img src="img/LOGO_USTA_AZUL.png" alt="Logo" class="logoustagrupo" width="200">

    <div class="admincreargrupo">

        <a href="index.html">
            <input class="cerrargrupo" type="submit" value="Cerrar Sesión">
        </a>

        <form class="asignatura">
            <label for="asignaturain" id="lblasignatura">Código </label>
            <input type="text" id="asignaturain" value="3259" class="inasignatura">
        </form>
        <br>
        <br>
        <form class="semestre">
            <label for="semestrein" id="lblsemestre">Apellidos </label>
            <input type="text" id="semestrein" value="Melo" class="insemestre">
        </form>
        <br>
        <br>
        <form class="profesorgrupo">
            <label for="profesorin" id="lblprofesor">Nombres </label>
            <input type="text" id="profesorin" value="Sergio" class="inprofesor">
        </form>
        <br>
        <br>

        <form class="cantidad">
            <label for="cantidadin" id="lblcantidad">Email </label>
            <input type="text" id="cantidadin" value="sergiomelo@gmail.com" class="incantidad">
        </form>

    </div>
    <br>
    <a href="verListaEstudiantes.html"><input class="enviarGrupo" type="submit" value="Guardar"></a>


    </form>
</body>

</html>

app/templates/app/editarGrupoAdmin.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>Editar Grupo como admin</title>
    <link rel="stylesheet" href="css/estilocrearestudiante.css">
</head>

<body>
    <h1> EDITAR GRUPO</h1>
    <hr>
    <br>
    <img src="img/profilephoto.png" alt="profilephoto" width="180">
    <img src="img/LOGO_USTA_AZUL.png" alt="Logo" class="logoustagrupo" width="200">

    <div class="admincreargrupo">

        <a href="index.html">
            <input class="cerrargrupo" type="submit" value="Cerrar Sesión">
        </a>

        <form class="asignatura">
            <label for="asignaturain" id="lblasignatura">Codigo del grupo </label>
            <input type="text" id="asignaturain" value="30059" class="inasignatura">
        </form>
        <br>
        <br>
        <form class="semestre">
            <label for="semestrein" id="lblsemestre">Asignatura </label>
            <input type="text" id="semestrein" value="Filosofía" class="insemestre">
        </form>
        <br>
        <br>
        <form class="profesorgrupo">
            <label for="profesorin" id="lblprofesor">Profesor </label>
            <input type="text" id="profesorin" value="Sergio Melo" class="inprofesor">
        </form>
        <br>
        <br>

        <form class="cantidad">
            <label for="cantidadin" id="lblcantidad">Semestre </label>
            <input type="text" id="cantidadin" value="IV" class="incantidad">
        </form>

    </div>
    <br>
    <a href="verGruposComoAdmin.html"><input class="enviarGrupo" type="submit" value="Guardar"></a>


    </form>
</body>

</html>

app/templates/app/estudiante.html
{% load static %}
<html>

<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Proyecto Cloud</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/estiloGrupoEstudiante.css' %}">
</head>

<body>

    <h1>Bienvenido Estudiante</h1>
    <hr>
    <img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
    <p class="InformacionUsuario">
        German Esteban Pardo Ramirez <br> id:300 <br> estudiante@gmail.com
    </p>
    <a href="{% url 'app:index' %}">
        <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
    </a>
    <br>
    <br>

    <div class="tabla">
        <table id="tablagrupos" border="1">
            <tr>
                <th>Id grupo</th>
                <th>Asignatura</th>
                <th>Semestre</th>
            </tr>
            <tr>
                <td><a href="verGrupoEstudiante.html">3-1agricultura</a></td>
                <td>Agricultura </td>
                <td>III</td>
            </tr>
            <tr>
                <td><a href="verGrupoEstudiante.html">2-1sistemas</a></td>
                <td>Sistemas
                </td>
                <td>II</td>
            </tr>
            <tr>
                <td><a href="verGrupoEstudiante.html">1-1filosofia</a></td>
                <td>Filosofía</td>
                <td>I</td>
            </tr>

        </table>

    </div>
    <br>

    <div class="logoes">
        <img src="{% static 'app/img/logo-social.png' %}" alt="logo-social">
    </div>

    <!-- <a href="https://guitarflash.com/?gfMP=1" target="_blank">
        <input class="Boton" type="submit" value="Ver grupo">
    </a> -->

    <!-- <br>
    <br>
    <br>
    <br>
    <br> <br> <br>
    <div id="BuscarGrupo">
        <label for="" class="Idgrupo">Id del grupo</label>
        <input type="text">
        <label for="" class="Idgrupo">Id del Estudiante</label>
        <input type="text">
    </div> -->


</body>

</html>

app/templates/app/index.html
{% load static %}

<html>
    <html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Proyecto Cloud</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
</head>

<body>
    <h1>BIENVENIDO A GRADER</h1>
    <form>
        <div class="autenticacion">

            <h2>USUARIO:</h2>
            <input type="" id="USUARIO">
            <br>
            <h2>CLAVE:</h2>
            <input type="password" id="password">
            <br>
            <br>
            <br>
        </div>
        <input class="Boton" type="submit" value="Enviar">
    </form>
    <br>
    <br>
    <br>
    <img src= "{% static 'app/img/AWS.jpg' %}" alt="AWS" width="150">
    <img class="usta" src=" {% static 'app/img/LOGO_USTA_AZUL.png' %}  " alt="Logo usta">
    <br>
    <a href="{% url 'app:profesor' %}" target="_blank">Ver como profesor</a>
    <br>
    <a href="{% url 'app:admin' %}" target="_blank">Ver como admin</a>
    <br>
    <a href="{% url 'app:estudiante' %}" target="_blank">Ver como estudiante</a>
    <br>

</body>

</html>

app/templates/app/listaDeCursosProfe.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Cursos</title>
    <link rel="stylesheet" href="css/estiloCrearProfesor.css">
</head>

<body>
    <div class="contenedor">
        <div class="title">
            <h1>Ver profesor</h1>
            <hr>
        </div>

        <div class="Datos">
            <div class="FotoPerfil">
                <img src="img/profilephoto.png" alt="profilephoto" width="180">
            </div>
            <div class="nombres">
                Apellido:Profe NombreProfe <br> id:Profe <br> Profe@gmail.com
            </div>
            <div class="cerrarsesion1">
                <a href="autenticacion.html">
                    <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
                </a>
            </div>
        </div>
        <div class="creacion">
            <div class="tabla">
                <table id="tablagrupos" border="1">
                    <tr>
                        <th>Semestre</th>
                        <th>Código</th>
                        <th>Asignatura</th>
                        <th>Cantidad Estudiantes</th>
                    </tr>
                    <tr>
                        <td>I</td>
                        <td>8009</td>
                        <td>Agricultura</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>II</td>
                        <td>8003</td>
                        <td>Sistemas</td>
                        <td>20</td>
                    </tr>
                    <tr>
                        <td>V</td>
                        <td>8002</td>
                        <td>Filosofía</td>
                        <td>24</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

</body>

</html>

app/templates/app/profesor.html
{% load static %}
<html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Profesor</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
</head>

<body>
    <h1>Bienvenido Profesor</h1>
    <hr>
    <p class="InformacionUsuario">
        Sergio Alejandro Suarez Guzman
        <br> id:200
        <br> profesor@gmail.com

    </p>
    <a href="{% url 'app:index' %}">
        <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
    </a>
    <img src="{% static 'app/img/profilephoto.png' %}" alt="profilephoto" width="180">
    <br>
    <br>
    <a href="crearAcividadProfesor.html" target="_blank">
        <input class="Boton" type="submit" value="Crear actividad">
    </a>
    <br>
    <br>
    <br>
    
    <br>
    <a href="verActividadProfesor.html" target="_blank">
        <input class="Boton" type="submit" value="Buscar">
    </a>
    <br>
    <br>

    <table class="tablaprofe" border="1">
        <tr>
            <th>Id grupo</th>
            <th>Asignatura</th>
            <th>Semestre</th>
        </tr>
        <tr>
            <td><a href="verGrupoProfesor.html">3-1agricultura</a></td>
            <td>Agricultura </td>
            <td>III</td>
        </tr>
        <tr>
            <td><a href="verGrupoProfesor.html">2-1sistemas</a></td>
            <td>Sistemas
            </td>
            <td>II</td>
        </tr>
        <tr>
            <td><a href="verGrupoProfesor.html">1-1filosofia</a></td>
            <td>Filosofía</td>
            <td>I</td>
        </tr>

    </table>
    <img class="ustaprofe" src="{% static 'app/img/LOGO_USTA_AZUL.png' %}" alt="Logo usta">
</body>

</html>

app/templates/app/verGrupoEstudiante.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notas grupo</title>
    <link rel="stylesheet" href="css/estilo.css">
    <link rel="stylesheet" href="css/estiloGrupoEstudiante.css">
</head>

<body>
    <div id="titulo">
        <h1>Notas de un grupo determinado</h1>
        <hr>
    </div>
    <div class="Datos">
        <div class="FotoPerfil">
            <img src="img/profilephoto.png" alt="profilephoto" width="180">
        </div>
        <div class="nombres">
            Semestre:IV <br> Asignatura:Agricultura <br> Profesor: Andres Melo
        </div>
        <div class="cerrarsesion1">
            <a href="autenticacion.html">
                <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
            </a>
        </div>
    </div>
    <class class="tabla">
        <table id="tablagrupos" border="1">
            <tr>
                <th>Actividad</th>
                <th>Descripción Actividad</th>
                <th>Nota</th>
            </tr>
            <tr>
                <td>300</td>
                <td>Matlab</td>
                <td>5 </td>
            </tr>
            <tr>
                <td>301</td>
                <td>Autoevaluación</td>
                <td>5</td>
            </tr>
            <tr>
                <td>302</td>
                <td>Parcial</td>
                <td>5</td>
            </tr>

        </table>
        
            

    </div>


    


</body>

</html>

app/templates/app/verGrupoProfesor.html
<html>
    <html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Ver grupo determinado Profesor</title>
    <link rel="stylesheet" href="css/estilo.css">
</head>

<body>
    <h1>Ver grupo determinado Profesor</h1>
    <hr>
    <p class="InformacionUsuario">
        Profesor: Sergio Alejandro Suarez Guzman
        <br> Código Grupo: Agricultura3-1
        <br> Asignatura: Agricultura
        <br>

    </p>
    <div>
        <a href="autenticacion.html">
            <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
        </a>
    </div>
    
    <img src="img/profilephoto.png" alt="profilephoto" width="180">
    <br>
    <br>

    </a>
    <br>
    <br>

    <table class="tablaprofe" border="1">
        <tr>
            <th>Apellidos</th>
            <th>Nombres</th>
            <th>Email</th>
        </tr>
        <tr>
            <td><a href="verEstudianteComoProfesor.html">Celis</a></td>
            <td>Sergio Andres</td>
            <td>Sergiomelo@gmail.com</td>
        </tr>
        <tr>
            <td><a href="verEstudianteComoProfesor.html">Cogua</a></td>
            <td>Andres Sergio</td>
            <td>andressuarez@gmail.com</td>
        </tr>
        <tr>
            <td><a href="verEstudianteComoProfesor.html">Dante</a></td>
            <td>German Andres</td>
            <td>germanmelo@gmail.com</td>
        </tr>
        <tr>
            <th>Id Actividad</th>

            <th>Descripción</th>
        </tr>

        <tr>
            <td><a href="verActividadProfesor.html">30440</a></td>
            <td>Trabajo matlab</td>
        </tr>
        <tr>
            <td><a href="verActividadProfesor.html">34401</a></td>
            <td>Parcial virtual</td>
        </tr>
        <tr>
            <td><a href="verActividadProfesor.html">344403</a></td>
            <td>Autoevaluacion</td>
        </tr>


    </table>
    <br>


    </table>

</body>

</html>

app/templates/app/verGruposComoAdmin.html
<html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Lista Grupos Admin</title>
    <link rel="stylesheet" href="css/estilo.css">
</head>

<body>
    <h1>Visualizar grupos en lista</h1>
    <hr>
    <p class="InformacionUsuario">
        Nombre Admin
        <br> id:Admin
        <br> admin@gmail.com

    </p>
    <a href="autenticacion.html">
        <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
    </a>
    <img src="img/profilephoto.png" alt="profilephoto" width="180">
    <br>

    <br>
    <br>
    <br>
    
    <br>
    <a href="verGrupoindividualAdmin.html">
        <input class="Boton" type="submit" value="Buscar">
    </a>
    <br>
    <br>

    <table class="tablaprofe" border="1">
        <tr class="cabeza">
            <th>Id grupo</th>
            <th>Código</th>
            <th>Asignatura</th>
            <th>Profesor</th>
            <th>Cantidad estudiantes</th>
            <th>Editar grupo</th>

        </tr>
        <tr>
            <td><a href="verGrupoindividualAdmin.html">3-1agricultura</a></td>
            <td>8009</td>
            <td>Agricultura </td>
            <td>Juan Melo</td>
            <td>2</td>
            <td>
                <a href="editarGrupoAdmin.html"><img src="img/editar.jpg" alt="editar" width="30"></a>
            </td>

        </tr>
        <tr>
            <td><a href="verGrupoindividualAdmin.html">2-1sistemas</a></td>
            <td>8003</td>
            <td>Sistemas </td>
            <td>Juan Melo</td>
            <td>20</td>
            <td>
                <a href="editarGrupoAdmin.html"><img src="img/editar.jpg" alt="editar" width="30"></a>
            </td>
        </tr>
        <tr>
            <td><a href="verGrupoindividualAdmin.html">1-1filosofia</a></td>
            <td>8002</td>
            <td>Filosofía</td>
            <td>Juan Melo</td>
            <td>24</td>
            <td>
                <a href="editarGrupoAdmin.html"><img src="img/editar.jpg" alt="editar" width="30"></a>
            </td>
        </tr>

    </table>
</body>

</html>

app/templates/app/verListaEstudiantes.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/estiloCrearProfesor.css">
    <title>Ver Estudiantes</title>
</head>

<body>
    <div class="contenedor">
        <div class="title">
            <h1>Ver Estudiantes</h1>
            <hr>
        </div>

        <div class="Datos">
            <div class="FotoPerfil">
                <img src="img/profilephoto.png" alt="profilephoto" width="180">
            </div>
            <div class="nombres">
                Admin <br> id:Admin <br> Admin@gmail.com
            </div>
            <div class="cerrarsesion1">
                <a href="autenticacion.html">
                    <input class="cerrarsesion" type="submit" value="Cerrar Sesión">
                </a>
            </div>
        </div>
        <div class="creacion">
            <div class="tabla">
                <table id="tablagrupos" border="1">
                    <tr class="cabezaestudiantes">
                        <th>Apellidos</th>
                        <th>Nombres</th>
                        <th>E-mail</th>
                        <th>Codigo</th>
                        <th>Editar</th>
                    </tr>
                    <tr>
                        <td>Apellido1</td>
                        <td>Nombre1</td>
                        <td>email1@email.com</td>
                        <td>001</td>
                        <td>
                            <a href="editarEstudiante.html"><img src="/img/editar.jpg" alt="editar" width="30"> </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Apellido2</td>
                        <td>Nombre2</td>
                        <td>email2@email.com</td>
                        <td>002</td>
                        <td>
                            <a href="editarEstudiante.html"><img src="/img/editar.jpg" alt="editar" width="30"> </a>
                        </td>
                    </tr>
                    <tr>
                        <td>Apellido3</td>
                        <td>Nombre3</td>
                        <td>email3@email.com</td>
                        <td>003</td>
                        <td>
                            <a href="editarEstudiante.html"><img src="/img/editar.jpg" alt="editar" width="30"> </a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</body>

</html>